#!/bin/sh
#PBS -N FuzzingWB
#PBS -o fsf.stdout.$PBS_JOBID
#PBS -e fsf.stderr.$PBS_JOBID

. ./youEdit.sh

echo ../testtrace -c $FSF_NUM_INPUTS -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_wb_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -t 500 -- ./${FSF_BENCH}WB $FSF_BENCH_ARGS

../testtrace -c $FSF_NUM_INPUTS -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_wb_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -t 500 -- ./${FSF_BENCH}WB $FSF_BENCH_ARGS

. ./exitCleanup.sh
