#!/bin/sh
#PBS -N FuzzingQemu
#PBS -o fsf.stdout.$PBS_JOBID
#PBS -e fsf.stderr.$PBS_JOBID

. ./youEdit.sh

echo ../testtrace -t 500 -c $FSF_NUM_INPUTS -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_qemu_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -Q -- ./${FSF_BENCH}Original $FSF_BENCH_ARGS

../testtrace -t 500 -c $FSF_NUM_INPUTS -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_qemu_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -Q -- ./${FSF_BENCH}Original $FSF_BENCH_ARGS

. ./exitCleanup.sh
