#!/bin/sh
#PBS -N FuzzingBaseline
#PBS -o fsf.stdout.$PBS_JOBID
#PBS -e fsf.stderr.$PBS_JOBID

. ./youEdit.sh

echo ../testtrace -B -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_baseline_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -c $FSF_NUM_INPUTS -t 500 -- ./${FSF_BENCH}Baseline $FSF_BENCH_ARGS

../testtrace -B -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_baseline_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -c $FSF_NUM_INPUTS -t 500 -- ./${FSF_BENCH}Baseline $FSF_BENCH_ARGS

. ./exitCleanup.sh
