#!/bin/sh
#PBS -N FuzzingDyninst
#PBS -o fsf.stdout.$PBS_JOBID
#PBS -e fsf.stderr.$PBS_JOBID

. ./youEdit.sh

echo ../testtrace -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_dyninst_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -c $FSF_NUM_INPUTS -t 500 -- ./${FSF_BENCH}OriginalDyninst $FSF_BENCH_ARGS

../testtrace -i $FSF_DUMP -s $FSF_SIZES -f ${FSF_RESULT_DIR}/res_${FSF_BENCH}_dyninst_${FSF_DAY}_$PBS_JOBID.txt -o ./outDIR_$PBS_JOBID -c $FSF_NUM_INPUTS -t 500 -- ./${FSF_BENCH}OriginalDyninst $FSF_BENCH_ARGS

. ./exitCleanup.sh
